---
title: "EDLD 653 Final"
author: "Chen Su"
format: 
  html:
    embed-resources: true
execute: 
  warning: false
---

### Part 1. API calls to chess.com 

```{r}
#| label: part-1-api-call

library(purrr)
library(httr)
library(jsonlite)

response <- GET('https://api.chess.com/pub/country/US/players')

player_list <- fromJSON(rawToChar(response$content))$players

# extract first 500 usernames
player_usernames <- player_list[1:500]

# create function to pull all the columns for each user
player_data_pull <- function(username) {
  
  info <- GET(paste0('https://api.chess.com/pub/player/', username))
  player_info <- fromJSON(rawToChar(info$content))
  
  stats <- GET(paste0('https://api.chess.com/pub/player/', username, '/stats'))
  player_stats <- fromJSON(rawToChar(stats$content))
  
  # Extract rapid stats if available
  rapid_stats <- player_stats$chess_rapid
  
  list(username = username, 
       name = ifelse(is.null(player_info$name), NA, player_info$name), 
       number_of_followers = player_info$followers, 
       location = player_info$location, 
       last_online = as.POSIXct(
         player_info$last_online, 
         origin = "1970-01-01", 
         tz = "UTC"
         ), 
      rapid_last_rating = ifelse(is.null(rapid_stats$last$rating), NA, rapid_stats$last$rating), 
      rapid_best_rating = ifelse(is.null(rapid_stats$best$rating), NA, rapid_stats$best$rating), 
      rapid_record_win = ifelse(is.null(rapid_stats$record$wins), NA, rapid_stats$record$wins),
      rapid_record_loss = ifelse(is.null(rapid_stats$record$losses), NA, rapid_stats$record$losses), 
      rapid_record_draw = ifelse(is.null(rapid_stats$record$draws), NA, rapid_stats$record$draws)
  )
}

players_df <- map_df(player_usernames, player_data_pull)

head(players_df)

```

*Part 1 Note: Microsoft Copilot was used to assist in troubleshooting the code for rapid stats and date.*



### Part 2. Identify & Remove Duplicate Files
```{r}
#| label: part-2-duplicates

library(dplyr)
library(digest)

files <- list.files("C:/Users/chens/Desktop/Spring 2026/edld653/edld653_final/question_2", 
           full.names = TRUE, recursive = TRUE)

# finding duplicates
file_hashes <- sapply(files, digest, file = TRUE)

hash_table <- data.frame(
  file = files,
  hash = file_hashes
)

originals <- hash_table[!duplicated(hash_table$hash), ]
duplicates <- hash_table[duplicated(hash_table$hash), ]

# create duplicate table
duplicate_table <- inner_join(originals, duplicates, by = "hash") |>
  select(originals = file.x,
         duplicates = file.y)

deleted_duplicates <- vapply(duplicate_table$duplicates, file.remove, logical(1))

# check 
length(list.files("C:/Users/chens/Desktop/Spring 2026/edld653/edld653_final/question_2", 
                  recursive = TRUE))

```

*Part 2 Note: Microsoft Copilot was used to assist in finding duplicates using digest package.*



### Part 3. Multiple Models
```{r}
#| label: models

library(tidyverse)
library(here)
library(lme4)

df <- read.csv(here("benchmarks.csv")) |>
    mutate(wave = case_when(
                  season == "fall" ~ 0,
                    season == "winter" ~ 1,
                    season == "spring" ~ 2)
    )


```


### Part 4. Slope Reliability Function

### Part 5. 95% Confidence Interval (CI) 

